apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30513
  type: NodePort